Update .gitlab-ci.yml

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -114,134 +114,134 @@ cache:
 
 # Validation: ------------------------------------------------------------------
 #SonarCheck:
-#  allow_failure: true
-#  only:
-#   - merge_requests
-#  except:
-#   - push
-#   - commit
-#  stage: SonarCheck
-#  image:
-#    name: sonarsource/sonar-scanner-cli:latest
-#    entrypoint: [""]
-#  cache:
-#    key: "${CI_JOB_NAME}"
-#    paths:
-#      - .sonar/cache
-#  before_script:
-#   - echo "Sonar Analysis"
-#  script:
-#   - . ./scripts/ci/sonar-check.sh
-#
-#.validate_script:
-#  script:
-#    - |
-# 
-#      export flag="validate"
-#      #next actions needs for populate_file_list can be executed
-#      git fetch origin $CI_MERGE_REQUEST_TARGET_BRANCH_NAME
-#      git fetch origin $CI_COMMIT_REF_NAME
-#      PARENT=$(git merge-base origin/$CI_COMMIT_REF_NAME origin/$CI_MERGE_REQUEST_TARGET_BRANCH_NAME)
-#      echo "[INFO] Parent commit for the MR is $PARENT"
-#      git merge --squash FETCH_HEAD
-#
-#      populate_file_list $PARENT HEAD
-#      
-#      
-#      git merge origin/$CI_MERGE_REQUEST_TARGET_BRANCH_NAME #merge target branch to work dir
-#      
-#      
-#  
-#
-#      if [[ ! -s $FILENAME_AM_STR ]]; then
-#        echo "[INFO] Files, changed in current scope of commits are not project files. $CI_JOB_NAME will NOT be executed."
-#      else
-#        echo "[INFO] Please see logs in artifact validate.sfdx.log."
-#        set -x
-#           chmod 777 ./scripts/ci/sfdx.wrapper.sh
-#   
-#          bash -x scripts/ci/sfdx.wrapper.sh validate_RunSpecifiedTests "$CI_MERGE_REQUEST_TARGET_BRANCH_NAME"
-#       fi
-#
-#      # checking if committed text files are with proper line endings (Fail the build if CRLF found).
-#      for file in $FILES_AM_COL; do
-#        if [[ ! $file =~ ^.*/staticresources/.*$ ]]; then  # check all but staticresources
-#          if (grep -qU $'\r' "$file"); then # -U prevents grep from stripping CR characters. $'\r' is a bash built-in for carriage return symbol.
-#            echo -e "[ERROR] Committed file with CRLF (Windows style) line endings, while only LF (Linux style) are allowed:\n$file"
-#            RC=100  # actually any non-zero code will do, but different error codes are better for local debug.
-#          fi
-#        else
-#          continue
-#        fi
-#      done
-#      exit $RC
-#  artifacts:
-#    when: always
-#    paths:
-#     # - "*.sfdx.log"
-#      - "tmp/*.txt"
-#      #- "MR.json"
+  allow_failure: true
+  only:
+    - merge_requests
+  except:
+   - push
+   - commit
+  stage: SonarCheck
+  image:
+    name: sonarsource/sonar-scanner-cli:latest
+    entrypoint: [""]
+  cache:
+  key: "${CI_JOB_NAME}"
+    paths:
+      - .sonar/cache
+  before_script:
+   - echo "Sonar Analysis"
+  script:
+   - . ./scripts/ci/sonar-check.sh
 
-#.deploy_script:
-#  script:
-#    - |
-#        set -x
-#        export flag="deploy"
-#        chmod 777 ./scripts/ci/sfdx.wrapper.sh
-#        if [[ $CI_PIPELINE_SOURCE == @(schedule|web) ]]; then
-#             echo "[INFO] Running full deployment if pipeline was started by schedule or 'Run' button on web interface."
-#             bash -x scripts/ci/sfdx.wrapper.sh deploy_full "$CI_COMMIT_REF_NAME"
-#        else 
-#           populate_file_list $CI_COMMIT_BEFORE_SHA HEAD 
-#           if [[ ! -s $FILENAME_AM_STR ]]; then
-#               echo "[INFO] Files, changed in current scope of commits are not project files. $CI_JOB_NAME will NOT be executed."
-#               exit 0
-#           else
-#              bash -x scripts/ci/sfdx.wrapper.sh deploy_without_testlevel "$CI_COMMIT_REF_NAME"
-#           fi  
-#        fi
-#  artifacts:
-#    when: always
-#    paths:
-#      - "tmp/*.txt"
-#
+.validate_script:
+  script:
+    - |
+ 
+      export flag="validate"
+      #next actions needs for populate_file_list can be executed
+      git fetch origin $CI_MERGE_REQUEST_TARGET_BRANCH_NAME
+      git fetch origin $CI_COMMIT_REF_NAME
+      PARENT=$(git merge-base origin/$CI_COMMIT_REF_NAME origin/$CI_MERGE_REQUEST_TARGET_BRANCH_NAME)
+      echo "[INFO] Parent commit for the MR is $PARENT"
+      git merge --squash FETCH_HEAD
 
-#VALIDATE:
-#  only:
-#    - merge_requests
-#  except:
-#    - push
-#    - commit
-#  
-#  stage: VALIDATE
-#  extends: .validate_script
-#
-#   
-#FullDeploy:
-#  extends: .deploy_script
-#  only:
-#    refs:
-#      - schedules
-#      - web
-#    variables:
-#      - $CI_COMMIT_REF_NAME =~ /^INT|^INF|^Callcenter/
-#  except:
-#      - merge_requests
-#  stage: Deploy
-#  timeout: 3h  # sum of run-tests.sh and deploy.sh timeouts.
+      populate_file_list $PARENT HEAD
+      
+      
+      git merge origin/$CI_MERGE_REQUEST_TARGET_BRANCH_NAME #merge target branch to work dir
+      
+      
+  
 
-#DeltaDeploy:
-#  extends: .deploy_script
-#  only:
-#    refs:
-#      - pushes
-#    variables:
-#      - $CI_COMMIT_REF_NAME =~ /^INT|^INF|^Callcenter/
-#  except:
-#      - merge_requests
-#  stage: Deploy
-#  timeout: 3h  # sum of run-tests.sh and deploy.sh timeouts.
-#  
+      if [[ ! -s $FILENAME_AM_STR ]]; then
+        echo "[INFO] Files, changed in current scope of commits are not project files. $CI_JOB_NAME will NOT be executed."
+      else
+        echo "[INFO] Please see logs in artifact validate.sfdx.log."
+        set -x
+           chmod 777 ./scripts/ci/sfdx.wrapper.sh
+   
+           bash -x scripts/ci/sfdx.wrapper.sh validate_RunSpecifiedTests "$CI_MERGE_REQUEST_TARGET_BRANCH_NAME"
+       fi
+
+      # checking if committed text files are with proper line endings (Fail the build if CRLF found).
+      for file in $FILES_AM_COL; do
+        if [[ ! $file =~ ^.*/staticresources/.*$ ]]; then  # check all but staticresources
+          if (grep -qU $'\r' "$file"); then # -U prevents grep from stripping CR characters. $'\r' is a bash built-in for carriage return symbol.
+            echo -e "[ERROR] Committed file with CRLF (Windows style) line endings, while only LF (Linux style) are allowed:\n$file"
+            RC=100  # actually any non-zero code will do, but different error codes are better for local debug.
+          fi
+        else
+          continue
+        fi
+      done
+      exit $RC
+  artifacts:
+    when: always
+    paths:
+     # - "*.sfdx.log"
+      - "tmp/*.txt"
+      #- "MR.json"
+
+.deploy_script:
+  script:
+    - |
+        set -x
+        export flag="deploy"
+        chmod 777 ./scripts/ci/sfdx.wrapper.sh
+        if [[ $CI_PIPELINE_SOURCE == @(schedule|web) ]]; then
+             echo "[INFO] Running full deployment if pipeline was started by schedule or 'Run' button on web interface."
+             bash -x scripts/ci/sfdx.wrapper.sh deploy_full "$CI_COMMIT_REF_NAME"
+        else 
+           populate_file_list $CI_COMMIT_BEFORE_SHA HEAD 
+           if [[ ! -s $FILENAME_AM_STR ]]; then
+               echo "[INFO] Files, changed in current scope of commits are not project files. $CI_JOB_NAME will NOT be executed."
+               exit 0
+           else
+              bash -x scripts/ci/sfdx.wrapper.sh deploy_without_testlevel "$CI_COMMIT_REF_NAME"
+           fi  
+        fi
+  artifacts:
+    when: always
+    paths:
+      - "tmp/*.txt"
+
+
+VALIDATE:
+  only:
+    - merge_requests
+  except:
+    - push
+    - commit
+  
+  stage: VALIDATE
+  extends: .validate_script
+
+   
+FullDeploy:
+  extends: .deploy_script
+  only:
+    refs:
+      - schedules
+      - web
+    variables:
+      - $CI_COMMIT_REF_NAME =~ /^INT|^INF|^Callcenter/
+  except:
+      - merge_requests
+  stage: Deploy
+  timeout: 3h  # sum of run-tests.sh and deploy.sh timeouts.
+
+DeltaDeploy:
+  extends: .deploy_script
+  only:
+    refs:
+      - pushes
+    variables:
+      - $CI_COMMIT_REF_NAME =~ /^INT|^INF|^Callcenter/
+  except:
+      - merge_requests
+  stage: Deploy
+  timeout: 3h  # sum of run-tests.sh and deploy.sh timeouts.
+  
 RUNTEST:
   only:
     - INF9.0
